# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1 


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby
  browser-tools: circleci/browser-tools@0.1.4

jobs: 
  test: 
    docker: 
      - image: circleci/ruby:2.6.3-stretch-node
    steps: 
      - checkout
      - run: 
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
			- install-chrome
			- install-chromedriver
      - run:
          name: RSpec
          command: bundle exec rspec -f d
      - store_artifacts:
          path: tmp/

workflows:
  version: 2
  workflow:
    jobs:
    - test

# What to do next? Set up a test job. Please see 
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
