# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1 


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby
  browsers: circleci/browser-tools@0.1.4

jobs: 
  test: 
    docker: 
      - image: circleci/ruby:2.6.3-stretch-node
    steps: 
      - checkout
      - run: 
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - browsers/install-chrome
      - browsers/install-chromedriver
      - run: sudo apt-get update; sudo apt-get install imagemagick
      - run:
          name: RSpec
          command: |
            set +e
            bundle exec rspec -f d
      - run: bin/pdf.sh
      - store_artifacts:
          path: tmp/
      # - run:
      #     name: Compress
      #     command: tar -cvzf screenshots.tar.gz tmp
      #     when: always
      # - store_artifacts:
      #     path: screenshots.tar.gz

workflows:
  version: 2
  workflow:
    jobs:
      - test
  daily:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
